WITH UnidadesPorArtForm AS (
    SELECT
        P.ID AS ID_PEDIDO,
        P.CODIGO_PEDIDO,
        P.FECHAH_GENERACION,
        P.ID_LOCAL,
        ACP.ID_ARTICULO,
        ACP.ID_FORMATO,
        SUM(ISNULL(ACP.CANT_FORM_BASE, 0)) AS Total_Esperadas
    FROM dbo.PEDIDOS P
    INNER JOIN dbo.ART_CONT_PEDIDO ACP ON P.ID = ACP.ID_PEDIDO
    WHERE P.ESTADO IN (16,17)
      AND ACP.CANT_FORM_BASE > 0
    GROUP BY P.ID, P.CODIGO_PEDIDO, P.ID_LOCAL, ACP.ID_ARTICULO, ACP.ID_FORMATO, P.FECHAH_GENERACION
),
UnidadesSolicitadasPorDia AS (
    SELECT
        UAF.ID_LOCAL,
        UAF.CODIGO_PEDIDO,
        CONVERT(VARCHAR(10), CONVERT(DATETIME, AM.FECHA_HORA, 120), 111) AS Fecha,
        SUM(UAF.Total_Esperadas) AS Total_Solicitadas
    FROM UnidadesPorArtForm UAF
    INNER JOIN PEDIDOS P ON UAF.ID_PEDIDO = P.ID
    INNER JOIN dbo.DESPACHOS D ON P.ID_DESPACHO = D.ID
    INNER JOIN (
        SELECT ID_DESPACHO, MIN(ID) AS ID, MIN(FECHA_HORA) AS FECHA_HORA
        FROM dbo.AVISOS_MERCADERIA
        WHERE TIPO_AV = 1
        GROUP BY ID_DESPACHO
    ) AM ON AM.ID_DESPACHO = D.ID
    GROUP BY
        UAF.ID_LOCAL,
        UAF.CODIGO_PEDIDO,
        CONVERT(VARCHAR(10), CONVERT(DATETIME, AM.FECHA_HORA, 120), 111)
),
UnidadesExpArtForm AS (
    SELECT
        P.ID AS ID_PEDIDO,
        ACM.ID_ARTICULO,
        ACM.ID_FORMATO,
        SUM(ISNULL(ACM.CANT_FORM_BASE, 0)) AS Cant_Expedida
    FROM dbo.PEDIDOS P
    INNER JOIN dbo.DESPACHOS D ON P.ID_DESPACHO = D.ID
    INNER JOIN dbo.AVISOS_MERCADERIA AM ON AM.ID_DESPACHO = D.ID
        AND (AM.COD_OC_PE_DE = P.CODIGO_PEDIDO
             OR AM.COD_OC_PE_DE = SUBSTRING(P.CODIGO_PEDIDO, 1, LEN(P.CODIGO_PEDIDO)-1))
    INNER JOIN dbo.ART_CONT_MERCADER ACM ON AM.ID = ACM.ID_MERCADERIA
    WHERE P.ESTADO IN (16,17)
      AND AM.TIPO_AV = 1
    GROUP BY P.ID, ACM.ID_ARTICULO, ACM.ID_FORMATO
),
PeCP AS (
    SELECT DISTINCT
        P.CODIGO_PEDIDO,
        P.ID_LOCAL,
        CONVERT(VARCHAR(10), CONVERT(DATETIME, AM.FECHA_HORA, 120), 111) AS Fecha
    FROM dbo.PEDIDOS P
    INNER JOIN dbo.ART_CONT_PEDIDO ACP ON P.ID = ACP.ID_PEDIDO
    INNER JOIN dbo.FORMATOS F ON ACP.ID_FORMATO = F.ID
    INNER JOIN dbo.DESPACHOS D ON P.ID_DESPACHO = D.ID
    INNER JOIN (
        SELECT ID_DESPACHO, MIN(ID) AS ID, MIN(FECHA_HORA) AS FECHA_HORA
        FROM dbo.AVISOS_MERCADERIA
        WHERE TIPO_AV = 1
        GROUP BY ID_DESPACHO
    ) AM ON AM.ID_DESPACHO = D.ID
    WHERE P.ESTADO IN (16,17)
      AND F.CANT_FORM_BASE != ACP.CANT_FORM_BASE
      AND ACP.NUM_UNIDADES_FORM IS NOT NULL
      AND ACP.NUM_UNIDADES_FORM > 0
      AND ACP.NUM_UNIDADES_FORM != ROUND(ACP.CANT_FORM_BASE / NULLIF(F.CANT_FORM_BASE, 0), 0)
),
PreparacionDiaria AS (
    SELECT
        --P.ID_LOCAL,
        P.CODIGO_PEDIDO,
        P.ESTADO,
        C.NOMBRE AS NOMBRE_LOCAL,
        CONVERT(VARCHAR(10), CONVERT(DATETIME, AM.FECHA_HORA, 120), 111) AS Fecha,
        AM.FECHA_HORA AS Fecha_Expedicion,
        US.Total_Solicitadas AS Total_Unidades_Solicitadas,
        SUM(ISNULL(UAF.Total_Esperadas, 0)) AS Total_Unidades_Calculadas,
        SUM(ISNULL(UEAF.Cant_Expedida, 0)) AS Total_Unidades_Expedidas,
        SUM(ISNULL(UAF.Total_Esperadas, 0)) - SUM(ISNULL(UEAF.Cant_Expedida, 0)) AS Total_Unidades_Faltantes
    FROM dbo.PEDIDOS P
    INNER JOIN dbo.CENTROS C ON P.ID_LOCAL = C.ID
    INNER JOIN dbo.DESPACHOS D ON P.ID_DESPACHO = D.ID
    INNER JOIN (
        SELECT ID_DESPACHO, MIN(ID) AS ID, MIN(FECHA_HORA) AS FECHA_HORA
        FROM dbo.AVISOS_MERCADERIA
        WHERE TIPO_AV = 1
        GROUP BY ID_DESPACHO
    ) AM ON AM.ID_DESPACHO = D.ID
    INNER JOIN UnidadesPorArtForm UAF ON UAF.ID_PEDIDO = P.ID
    LEFT JOIN UnidadesExpArtForm UEAF
        ON UEAF.ID_PEDIDO = P.ID
        AND UEAF.ID_ARTICULO = UAF.ID_ARTICULO
        AND UEAF.ID_FORMATO = UAF.ID_FORMATO
    INNER JOIN UnidadesSolicitadasPorDia US
        ON US.Fecha = CONVERT(VARCHAR(10), CONVERT(DATETIME, AM.FECHA_HORA, 120), 111)
        AND US.ID_LOCAL = P.ID_LOCAL
        AND US.CODIGO_PEDIDO = P.CODIGO_PEDIDO
    WHERE P.ESTADO IN (16,17)
    GROUP BY
        P.ID_LOCAL,
        P.CODIGO_PEDIDO,
        P.ESTADO,
        C.NOMBRE,
        CONVERT(VARCHAR(10), CONVERT(DATETIME, AM.FECHA_HORA, 120), 111),
        AM.FECHA_HORA,
        US.Total_Solicitadas
)
SELECT * FROM PreparacionDiaria;