SELECT
    i.FECHA_H_CREACION,
    i.NOMBRE AS NOMBRE_INVENTARIO,
    ai.NOMBRE_USUARIO AS USUARIO,
    ui.NOMBRE_UBICACION AS UBICACION,
    ai.ETIQ_CONT_INVENTA AS ETIQUETA,
    a.CODE_ERP AS CODIGO,
    a.DESCRIPCION,
    fo.CANT_FORM_BASE AS UnidadPorCaja,
    f.CODE_FORMATO AS formatoOrigen,
    ai.CANT_FORMATO_ORI,
    f.CANT_FORM_BASE * ai.CANT_FORMATO_ORI AS unidadesOrigen,
    f.CANT_FORM_BASE * ai.CANT_FORMATO_INV AS ubidadesInventariadas,
    (f.CANT_FORM_BASE * ai.CANT_FORMATO_INV) - (f.CANT_FORM_BASE * ai.CANT_FORMATO_ORI) AS unidadesDiferencia,
    ai.FECHA_REALIZADO AS FH_CONTEO_LINEA
FROM INVENTARIOS i
INNER JOIN ART_INVENTARIO ai
    ON ai.ID_INVENTARIO = i.ID
INNER JOIN UBICACIONES_INV ui
    ON ui.ID_INVENTARIO = i.ID
   AND ui.ID = ai.ID_UBICACION
INNER JOIN ARTICULOS a
    ON a.ID = ai.ID_ART_INVENTA
INNER JOIN FORMATOS f
    ON f.ID = ai.ID_FORMATO
LEFT JOIN FORMATOS fo
    ON fo.ID_ARTICULO = ai.ID_ART_INVENTA
   AND fo.CODE_FORMATO = 'C'
WHERE
    ai.ESTADO = 2
    AND SUBSTRING(i.FECHA_H_CREACION, 1, 10) >= '2025/08/01'
    AND SUBSTRING(i.FECHA_H_CREACION, 1, 10) <= '2025/12/01'
ORDER BY
    1, 2, 14;
