SELECT DISTINCT
    x.FECHA,
    x.TIPO_ORIGEN,
    x.TIPO_OE,
    x.ORIGEN,
    x.MATRICULA,
    x.HORA_LLEGADA_CAMION,
    x.FH_CREACION_CAMION,
    x.FH_INI_ADMIN,
    x.FH_FIN_ADMIN,
    x.FH_INI_FISICA,
    x.FH_FIN_FISICA,
    x.FH_SALIDA_CAMION
FROM (
    SELECT
        acm.ID,
        SUBSTRING(av.FECHA_HORA, 1, 10) AS FECHA,
        CASE
            WHEN tc.ID = 16 THEN 'PROVEEDOR'
            WHEN tc.ID = 18 THEN 'SUCURSAL'
            ELSE tc.CODIGO
        END AS TIPO_ORIGEN,
        cen.NOMBRE AS ORIGEN,
        tp.NOMBRE AS TIPO_OE,
        ca.MATRICULA,
        ca.FECHAH_ENTRADA AS HORA_LLEGADA_CAMION,      -- << CAMBIO PEDIDO
        ca.FECHAH_ENTRADA AS FH_CREACION_CAMION,
        adm.FECHAH_INICIO AS FH_INI_ADMIN,
        adm.FECHAH_FIN AS FH_FIN_ADMIN,
        fis.FH_INI_FISICA,
        fis.FH_FIN_FISICA,
        ca.FECHAH_SALIDA AS FH_SALIDA_CAMION
    FROM AVISOS_MERCADERIA av
    INNER JOIN CAMIONES ca ON ca.ID = av.ID_CAMION
    INNER JOIN MISIONES m ON m.ID_CAMION = ca.ID
    INNER JOIN OPERACION_RF_RECEP orr ON orr.ID_MISION = m.ID
    INNER JOIN OPERACIONES_RF adm ON adm.ID = orr.ID
    INNER JOIN ART_CONT_MERCADER acm ON acm.ID_MERCADERIA = av.ID
    INNER JOIN UL_MAYOR_MERCADER um ON um.ID = acm.ID_UL_MAYOR
    INNER JOIN ORDENES_ENTRADA oe ON oe.ID = av.ID_OC_RECIBIDA
    INNER JOIN ORDENES_ENTRAD_REC oerec ON oerec.ID_ORDEN_ENTRADA = oe.ID
    INNER JOIN TIPOS_ORDENES_ENTRADA tp ON tp.TIPO_EXTERNO = oe.TIPO_EXTERNO
    INNER JOIN CENTROS cen ON cen.ID = oe.ID_ORIGEN
    INNER JOIN TIPOS_CENTRO tc ON tc.ID = cen.ID_TIPO_CENTRO

    LEFT JOIN (
        SELECT
            dd.ID_ORDEN_ENTRADA,
            MIN(fis.FECHAH_INICIO) AS FH_INI_FISICA,
            MAX(fis.FECHAH_FIN) AS FH_FIN_FISICA
        FROM OPERACIONES_RF fis
        INNER JOIN MOV_RECEP_FISICA_GC mrfg ON mrfg.ID_OPERACION = fis.ID
        INNER JOIN DESCARGAS_DETALLE dd ON dd.ID_DESCARGA = mrfg.ID_DESCARGA
        GROUP BY dd.ID_ORDEN_ENTRADA
    ) fis ON fis.ID_ORDEN_ENTRADA = oe.ID

    WHERE
        av.TIPO_AV = 2
        AND um.ETIQUETA <> 'UNIDADESLOGISTICAS'
        AND av.FECHA_HORA >= '2025/10/01'
        AND av.FECHA_HORA <= '2025/12/01'
) x
ORDER BY 1, 7;
